language: python
python:
  - "3.6"
  - "3.7"
# earlier versions not supported by black
# command to install dependencies
# Current workaround for running Python 3.7 tests
sudo: required
dist: xenial
install:
  - pip install -r requirements.txt
script:
  - pytest # or py.test for Python versions 3.5 and below
os:
  - linux
# may add osx later if it works - currently having issues