language: python
python:
  - "3.6" # earlier versions not supported by black
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - pytest # or py.test for Python versions 3.5 and below