language: python
python:
  - "3.5"
  - "3.6"
#  - "3.7" Will not include 3.7 support for now - need to add xenial with sudo
# earlier versions not supported by black
# command to install dependencies
# Current workaround for running Python 3.7 tests
# sudo: required
# dist: xenial
install:
  - pip install -r requirements.txt
script:
  - pytest stockscore/tests --runslow # or py.test for Python versions 3.5 and below
os:
  - linux
# may add osx later if it works - currently having issues